import React, { createContext, useContext, useState, useEffect } from 'react';

type Lang = 'es' | 'en';

const translations: Record<Lang, Record<string, string>> = {
  es: {
    'navbar.language': 'Idioma',
    'navbar.search.placeholder': 'Buscar estudiantes, predicciones, ayuda...',
    'navbar.systemTitle': 'Sistema de Predicción',
    'navbar.systemSubtitle': 'Académica — Interfaz limpia',
    'navbar.logout': 'Salir',
    'sidebar.panel': 'Panel Principal',
    'sidebar.predicciones': 'Predicciones',
    'sidebar.estudiantes': 'Estudiantes',
    'sidebar.soporte': 'Soporte',
    'sidebar.opcionesRapidas': 'Opciones rápidas',
    'soporte.title': 'Soporte',
    'soporte.subtitle': 'Obtén ayuda y soporte técnico',
    'soporte.tab.faq': 'Preguntas Frecuentes',
    'soporte.tab.contact': 'Formulario de Contacto',
    'soporte.tab.tickets': 'Mis Tickets',
    'soporte.tab.resources': 'Recursos',
  /* Accessibility menu translations */
  'accessibility.title': 'Menú de Accesibilidad',
  'accessibility.auditiva': 'Accesibilidad Auditiva',
  'accessibility.visual': 'Accesibilidad Visual',
  'accessibility.motriz': 'Accesibilidad Motriz',
  'accessibility.subtitles': 'Subtítulos en videos',
  'accessibility.transcripts': 'Transcripciones textuales',
  'accessibility.audioControl': 'Control de audio (pausar/detener)',
  'accessibility.visualAlerts': 'Alertas visuales en lugar de sonidos',
  'accessibility.signLanguage': 'Video-intérprete en lengua de señas',
  'accessibility.highContrast': 'Alto contraste',
  'accessibility.darkMode': 'Modo oscuro',
  'accessibility.textSize': 'Tamaño de texto',
  'accessibility.fontType': 'Tipo de fuente',
  'accessibility.customColors': 'Colores personalizados',
  'accessibility.colorCustomization': 'Personalización de Colores',
  'accessibility.colorPresets': 'Paletas predefinidas',
  'accessibility.backgroundColor': 'Color de fondo',
  'accessibility.textColor': 'Color de texto',
  'accessibility.primaryColor': 'Color primario',
  'accessibility.secondaryColor': 'Color secundario',
  'accessibility.accentColor': 'Color de acento',
  'accessibility.borderColor': 'Color de bordes',
  'accessibility.colorPreview': 'Vista previa del esquema de color:',
  'accessibility.primaryButton': 'Botón Primario',
  'accessibility.accentButton': 'Botón Acento',
  'accessibility.textToSpeech': 'Lectura por voz (text-to-speech)',
  'accessibility.linkHighlight': 'Resaltado de enlaces y foco visible',
  'accessibility.textSpacing': 'Espaciado entre letras y líneas',
  'accessibility.keyboardNav': 'Navegación por teclado (Tab, Enter, Esc)',
  'accessibility.largeButtons': 'Botones grandes',
  'accessibility.customShortcuts': 'Atajos de teclado personalizados',
  'accessibility.voiceControl': 'Control por voz / dictado',
  'accessibility.blockAutoScroll': 'Bloquear auto-scroll o auto-reproducción',
  'accessibility.reset': 'Restablecer',
  'accessibility.apply': 'Aplicar',
  'accessibility.closeMenu': 'Cerrar menú de accesibilidad',
  'accessibility.small': 'Pequeño',
  'accessibility.large': 'Grande',
  'accessibility.compact': 'Compacto',
  'accessibility.spacious': 'Espacioso',
  'accessibility.readText': 'Leer Texto',
  'accessibility.stopReading': 'Detener Voz',
  'accessibility.voiceControlButton': 'Control Voz',
  'accessibility.noTextSelected': 'No hay texto seleccionado',
  'accessibility.readingStarted': 'Lectura iniciada',
  'accessibility.readingStopped': 'Lectura detenida',
  'accessibility.voiceActivated': 'Control por voz activado. Hable para navegar.',
  'accessibility.voiceDeactivated': 'Control por voz desactivado',
  'accessibility.navigateEstudiantes': 'Navegando a Estudiantes',
  'accessibility.navigateSoporte': 'Navegando a Soporte',
  'accessibility.navigatePredicciones': 'Navegando a Predicciones',
  'accessibility.navigatePanel': 'Navegando al Panel',
  'accessibility.cerrandoSesion': 'Cerrando sesión',
  'accessibility.idiomaIngles': 'Idioma cambiado a Inglés',
  'accessibility.idiomaEspanol': 'Idioma cambiado a Español',
  'accessibility.leyendoSeleccion': 'Leyendo selección',
  'accessibility.opened': 'Menú de accesibilidad abierto',
  'accessibility.closed': 'Menú de accesibilidad cerrado',
  'accessibility.openMenu': 'Abrir menú de accesibilidad',
    'soporte.form.asunto': 'Asunto',
    'soporte.form.correo': 'Correo electrónico',
    'soporte.form.mensaje': 'Describe tu problema',
    'soporte.form.enviar': 'Enviar',
    'soporte.tickets.empty': 'Aún no tienes tickets.',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Resumen del sistema de predicción académica',
    'dashboard.totalEstudiantes': 'Total Estudiantes',
    'dashboard.prediccionesGeneradas': 'Predicciones Generadas',
    'dashboard.riesgoAlto': 'Riesgo Alto',
    'dashboard.generarPrediccion': 'Generar Nueva Predicción',
    'dashboard.verReportes': 'Ver Reportes',
    'dashboard.exportarDatos': 'Exportar Datos',
  'dashboard.errorExportar': 'Error al exportar datos',
  'dashboard.generarReporteMensaje': 'Generando reporte de predicciones...\nEsta funcionalidad estará disponible pronto.',
  'dashboard.bienvenida': 'Bienvenido de nuevo',
  'dashboard.sistemaActivo': 'Sistema activo',
    'estudiantes.title': 'Estudiantes',
    'estudiantes.subtitle': 'Gestión de estudiantes y sus datos académicos',
  'estudiantes.lista': 'Lista de Estudiantes',
  'estudiantes.listaTitulo': 'Lista de Estudiantes',
  'estudiantes.agregar': 'Agregar Estudiante',
  'estudiantes.buscar': 'Buscar estudiantes...',
  'estudiantes.buscarPlaceholder': 'Buscar estudiantes...',
  'estudiantes.colEstudiante': 'Estudiante',
  'estudiantes.colEmail': 'Email',
  'estudiantes.colSemestre': 'Semestre',
  'estudiantes.colNivelRiesgo': 'Nivel de Riesgo',
  'estudiantes.colAcciones': 'Acciones',
  'estudiantes.sinDatos': 'Sin datos',
  'estudiantes.verDetalles': 'Ver Detalles',
  'estudiantes.generarPrediccion': 'Generar Predicción',
  'estudiantes.eliminar': 'Eliminar',
  'estudiantes.modalTitle': 'Agregar Nuevo Estudiante',
  'estudiantes.labelId': 'Cédula/ID',
  'estudiantes.placeholderId': '1234567890',
  'estudiantes.labelNombres': 'Nombres',
  'estudiantes.placeholderNombres': 'Juan Carlos',
  'estudiantes.labelApellidos': 'Apellidos',
  'estudiantes.placeholderApellidos': 'Pérez García',
  'estudiantes.labelEmail': 'Email',
  'estudiantes.placeholderEmail': 'estudiante@universidad.edu',
  'estudiantes.labelSemestre': 'Semestre Actual',
  'estudiantes.placeholderSemestre': 'Ingrese el semestre actual (ej. 1)',
  'estudiantes.titleSemestre': 'Semestre actual del estudiante',
  'estudiantes.cancelar': 'Cancelar',
  'estudiantes.guardando': 'Guardando...',
  'estudiantes.guardarEstudiante': 'Guardar Estudiante',
  'estudiantes.errorCargar': 'Error al cargar estudiantes',
  'estudiantes.completeCampos': 'Por favor complete todos los campos obligatorios',
  'estudiantes.errorCrear': 'Error al crear estudiante',
  'estudiantes.verDetallesDe': 'Ver detalles de',
  'estudiantes.enDesarrollo': 'Esta funcionalidad está en desarrollo.',
  'estudiantes.generandoPara': 'Generando predicción para',
  'estudiantes.confirmEliminar': '¿Está seguro de eliminar a',
  'estudiantes.errorEliminar': 'Error al eliminar estudiante',
  'estudiantes.limpiarBusqueda': 'Limpiar búsqueda',
  'estudiantes.resultadosBusqueda': 'Mostrando {count} resultado(s) para "{term}"',
  'estudiantes.registrados': 'estudiantes registrados',
  'estudiantes.activos': 'Activos',
  'estudiantes.enRiesgo': 'En Riesgo',
  'estudiantes.semestrePromedio': 'Semestre Promedio',
  'estudiantes.bienvenidaVacio': '¡Bienvenido,',
  'estudiantes.noEstudiantesRegistrados': 'Aún no hay estudiantes registrados en el sistema.',
  'estudiantes.agregarPrimero': 'Agregar el primer estudiante',
  'estudiantes.noResultados': 'No se encontraron resultados',
  'estudiantes.noCoincidencias': 'No hay estudiantes que coincidan con tu búsqueda "{term}".',
  'estudiantes.modalPrimerEstudiante': '¡Perfecto {userName}! Vamos a registrar el primer estudiante.',
  'estudiantes.modalAgregarEstudiante': 'Agregando estudiante #{number} al sistema',
  'login.completeCampos': 'Por favor complete todos los campos',
  'login.errorIniciar': 'Error al iniciar sesión',
  'login.email': 'Correo Electrónico',
  'login.emailPlaceholder': 'usuario@universidad.edu',
  'login.password': 'Contraseña',
  'login.passwordPlaceholder': '••••••••',
  'login.iniciando': 'Iniciando sesión...',
  'login.iniciarSesion': 'Iniciar Sesión',
  'login.noTienesCuenta': '¿No tienes cuenta?',
  'login.registrateAqui': 'Regístrate aquí',
  'login.demo': 'Demo',
  'login.demoDescription': 'Usa cualquier email/contraseña para acceder en modo demostración.',
    'predicciones.title': 'Predicciones de Riesgo',
    'predicciones.subtitle': 'Análisis de riesgo académico de los estudiantes',
  'predicciones.generarNuevas': 'Generar Nuevas Predicciones',
  'predicciones.alertGenerarNuevas': 'Generando nuevas predicciones para todos los estudiantes...\nEsta funcionalidad estará disponible cuando el backend esté completo.',
  'predicciones.verDetallesDe': 'Ver detalles de predicción',
  'predicciones.errorDescargar': 'El reporte no está disponible aún',
  'predicciones.confirmRecalcular': '¿Desea recalcular la predicción para',
  'predicciones.recalculando': 'Recalculando predicción...',
  'predicciones.generadasTitulo': 'Predicciones Generadas',
  'predicciones.filtrarLabel': 'Filtrar predicciones por nivel de riesgo',
  'predicciones.optionTodos': 'Todos los niveles',
  'predicciones.optionAlto': 'Riesgo Alto',
  'predicciones.optionMedio': 'Riesgo Medio',
  'predicciones.optionBajo': 'Riesgo Bajo',
  'predicciones.fecha': 'Fecha',
  'predicciones.factoresClave': 'Factores Clave',
  'predicciones.verDetalles': 'Ver Detalles',
  'predicciones.descargando': 'Descargando...',
  'predicciones.generarReporte': 'Generar Reporte',
  'predicciones.recalcular': 'Recalcular',
  'predicciones.noEncontradas': 'No se encontraron predicciones con el filtro seleccionado.',
  'predicciones.nuevaPrediccion': 'Nueva Predicción',
  'predicciones.seleccionarEstudiante': 'Seleccionar Estudiante',
  'predicciones.seleccioneEstudiante': 'Por favor, seleccione un estudiante',
  'predicciones.seleccioneOpcion': 'Seleccione una opción...',
  'predicciones.notasPromedio': 'Promedio de Notas',
  'predicciones.rangoNotasPromedio': 'Escala del 0.0 al 10.0',
  'predicciones.asistencia': 'Asistencia (%)',
  'predicciones.rangoAsistencia': 'Porcentaje de 0 a 100',
  'predicciones.horasEstudio': 'Horas de Estudio Semanales',
  'predicciones.rangoHorasEstudio': 'Horas por semana',
  'predicciones.participacion': 'Participación en Clase',
  'predicciones.participacionBaja': 'Baja',
  'predicciones.participacionMedia': 'Media',
  'predicciones.participacionAlta': 'Alta',
  'predicciones.entregas': 'Entrega de Tareas (%)',
  'predicciones.rangoEntregas': 'Porcentaje de 0 a 100',
  'predicciones.examenes': 'Promedio de Exámenes',
  'predicciones.rangoExamenes': 'Escala del 0.0 al 10.0',
  'predicciones.prediccionCreada': 'Predicción creada exitosamente',
  'predicciones.errorCrear': 'Error al crear la predicción',
  'common.cancelar': 'Cancelar',
  'common.guardar': 'Guardar',
  'common.guardando': 'Guardando...',
  'register.title': 'Crear Cuenta',
  'register.subtitle': 'Sistema de Predicción Académica',
  'register.nombres': 'Nombres',
  'register.apellidos': 'Apellidos',
  'register.email': 'Correo Electrónico',
  'register.password': 'Contraseña',
  'register.confirmPassword': 'Confirmar Contraseña',
  'register.placeholderNombres': 'Juan',
  'register.placeholderApellidos': 'Pérez',
  'register.placeholderEmail': 'usuario@universidad.edu',
  'register.placeholderPassword': '••••••••',
  'register.registrando': 'Registrando...',
  'register.registrarse': 'Registrarse',
  'register.yaTienesCuenta': '¿Ya tienes cuenta?',
  'register.iniciaSesion': 'Inicia sesión aquí',
  'register.completeCampos': 'Por favor complete todos los campos',
  'register.passwordNoCoincide': 'Las contraseñas no coinciden',
  'register.passwordMinLength': 'La contraseña debe tener al menos 6 caracteres',
  'profile.title': 'Editar perfil',
  'profile.nombres': 'Nombres',
  'profile.apellidos': 'Apellidos',
  'profile.email': 'Correo Electrónico',
  'profile.telefono': 'Teléfono',
  'profile.direccion': 'Dirección',
  'profile.fechaNacimiento': 'Fecha de Nacimiento',
  'profile.emailNoEditable': 'El email no puede ser modificado',
  'profile.camposNoEditables': 'ID, semestre, carrera y promedio son gestionados por la institución',
  'profile.actualizado': 'Perfil actualizado correctamente',
  'profile.errorActualizar': 'Error al actualizar perfil',
  'profile.actualizando': 'Actualizando...',
  'profile.actualizar': 'Actualizar',
  'profile.cerrar': 'Cerrar',
  'footer.info': 'Universidad · Información institucional',
  'footer.soporte': 'Soporte',
  'footer.politicas': 'Políticas',
  'calificaciones.title': 'Registro de Calificaciones',
  'calificaciones.asignatura': 'Asignatura',
  'calificaciones.estudiante': 'Estudiante',
  'calificaciones.periodo': 'Período Académico',
  'calificaciones.tipoEvaluacion': 'Tipo de Evaluación',
  'calificaciones.nota': 'Nota',
  'calificaciones.registrar': 'Registrar Calificación',
  'calificaciones.seleccionar': 'Seleccionar...',
  'calificaciones.acciones': 'Acciones',
  'calificaciones.editar': 'Editar',
  'calificaciones.eliminar': 'Eliminar',
  'calificaciones.fecha': 'Fecha',
  'calificaciones.historial': 'Historial de Calificaciones',
  'estudiante.portalTitle': 'Portal Estudiante',
  'estudiante.bienvenido': 'Bienvenido',
  'estudiante.cerrarSesion': 'Cerrar sesión',
  'estudiante.promedioGeneral': 'Promedio General',
  'estudiante.nivelRiesgo': 'Nivel de Riesgo',
  'estudiante.materias': 'Materias',
  'estudiante.asistenciaPromedio': 'Asistencia Promedio',
  'estudiante.misCalificaciones': 'Mis Calificaciones',
  'estudiante.miAsistencia': 'Mi Asistencia',
  'estudiante.semestre': 'Semestre',
  'estudiante.recomendacionesPersonalizadas': 'Recomendaciones Personalizadas',
  'estudiante.riesgoBajo': 'Bajo',
  'estudiante.riesgoMedio': 'Medio',
  'estudiante.riesgoAlto': 'Alto',
  'estudiante.recomendacion1': 'Mantén un buen rendimiento en Programación',
  'estudiante.recomendacion2': 'Refuerza tus conocimientos en Física',
  'estudiante.recomendacion3': 'Mejora tu asistencia en Física',
  'estudiante.recomendacion4': 'Continúa con tu excelente asistencia general',
  'dashboard.distribucionRiesgo': 'Distribución de Riesgo',
  'dashboard.riesgoBajo': 'Riesgo Bajo',
  'dashboard.riesgoMedio': 'Riesgo Medio',
  'dashboard.accionesRapidas': 'Acciones Rápidas',
  },
  en: {
    'navbar.language': 'Language',
    'navbar.search.placeholder': 'Search students, predictions, help...',
    'navbar.systemTitle': 'Prediction System',
    'navbar.systemSubtitle': 'Academic — Clean UI',
    'navbar.logout': 'Logout',
    'sidebar.panel': 'Dashboard',
    'sidebar.predicciones': 'Predictions',
    'sidebar.estudiantes': 'Students',
    'sidebar.soporte': 'Support',
    'sidebar.opcionesRapidas': 'Quick actions',
    'soporte.title': 'Support',
    'soporte.subtitle': 'Get help and technical support',
    'soporte.tab.faq': 'FAQ',
    'soporte.tab.contact': 'Contact Form',
    'soporte.tab.tickets': 'My Tickets',
    'soporte.tab.resources': 'Resources',
  /* Accessibility menu translations */
  'accessibility.title': 'Accessibility Menu',
  'accessibility.auditiva': 'Auditory Accessibility',
  'accessibility.visual': 'Visual Accessibility',
  'accessibility.motriz': 'Motor Accessibility',
  'accessibility.subtitles': 'Video subtitles',
  'accessibility.transcripts': 'Text transcripts',
  'accessibility.audioControl': 'Audio control (pause/stop)',
  'accessibility.visualAlerts': 'Visual alerts instead of sounds',
  'accessibility.signLanguage': 'Sign language video interpreter',
  'accessibility.highContrast': 'High contrast',
  'accessibility.darkMode': 'Dark mode',
  'accessibility.textSize': 'Text size',
  'accessibility.fontType': 'Font type',
  'accessibility.customColors': 'Custom colors',
  'accessibility.colorCustomization': 'Color Customization',
  'accessibility.colorPresets': 'Preset palettes',
  'accessibility.backgroundColor': 'Background color',
  'accessibility.textColor': 'Text color',
  'accessibility.primaryColor': 'Primary color',
  'accessibility.secondaryColor': 'Secondary color',
  'accessibility.accentColor': 'Accent color',
  'accessibility.borderColor': 'Border color',
  'accessibility.colorPreview': 'Color scheme preview:',
  'accessibility.primaryButton': 'Primary Button',
  'accessibility.accentButton': 'Accent Button',
  'accessibility.textToSpeech': 'Text-to-speech',
  'accessibility.linkHighlight': 'Link highlighting and visible focus',
  'accessibility.textSpacing': 'Letter/line spacing',
  'accessibility.keyboardNav': 'Keyboard navigation (Tab, Enter, Esc)',
  'accessibility.largeButtons': 'Large buttons',
  'accessibility.customShortcuts': 'Custom keyboard shortcuts',
  'accessibility.voiceControl': 'Voice control / dictation',
  'accessibility.blockAutoScroll': 'Block auto-scroll or auto-play',
  'accessibility.reset': 'Reset',
  'accessibility.apply': 'Apply',
  'accessibility.closeMenu': 'Close accessibility menu',
  'accessibility.small': 'Small',
  'accessibility.large': 'Large',
  'accessibility.compact': 'Compact',
  'accessibility.spacious': 'Spacious',
  'accessibility.readText': 'Read Text',
  'accessibility.stopReading': 'Stop Reading',
  'accessibility.voiceControlButton': 'Voice Control',
  'accessibility.noTextSelected': 'No text selected',
  'accessibility.readingStarted': 'Reading started',
  'accessibility.readingStopped': 'Reading stopped',
  'accessibility.voiceActivated': 'Voice control activated. Speak to navigate.',
  'accessibility.voiceDeactivated': 'Voice control deactivated',
  'accessibility.navigateEstudiantes': 'Navigating to Students',
  'accessibility.navigateSoporte': 'Navigating to Support',
  'accessibility.navigatePredicciones': 'Navigating to Predictions',
  'accessibility.navigatePanel': 'Navigating to Dashboard',
  'accessibility.cerrandoSesion': 'Logging out',
  'accessibility.idiomaIngles': 'Language changed to English',
  'accessibility.idiomaEspanol': 'Language changed to Spanish',
  'accessibility.leyendoSeleccion': 'Reading selection',
  'accessibility.opened': 'Accessibility menu opened',
  'accessibility.closed': 'Accessibility menu closed',
  'accessibility.openMenu': 'Open accessibility menu',
    'soporte.form.asunto': 'Subject',
    'soporte.form.correo': 'Email',
    'soporte.form.mensaje': 'Describe your issue',
    'soporte.form.enviar': 'Send',
    'soporte.tickets.empty': "You don't have tickets yet.",
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Academic prediction system overview',
    'dashboard.totalEstudiantes': 'Total Students',
    'dashboard.prediccionesGeneradas': 'Generated Predictions',
    'dashboard.riesgoAlto': 'High Risk',
    'dashboard.generarPrediccion': 'Generate New Prediction',
    'dashboard.verReportes': 'View Reports',
    'dashboard.exportarDatos': 'Export Data',
  'dashboard.errorExportar': 'Error exporting data',
  'dashboard.generarReporteMensaje': 'Generating prediction report...\nThis functionality will be available soon.',
  'dashboard.bienvenida': 'Welcome back',
  'dashboard.sistemaActivo': 'System active',
    'estudiantes.title': 'Students',
    'estudiantes.subtitle': 'Management of students and academic data',
  'estudiantes.lista': 'Students List',
  'estudiantes.listaTitulo': 'Students List',
  'estudiantes.agregar': 'Add Student',
  'estudiantes.buscar': 'Search students...',
  'estudiantes.buscarPlaceholder': 'Search students...',
  'estudiantes.colEstudiante': 'Student',
  'estudiantes.colEmail': 'Email',
  'estudiantes.colSemestre': 'Semester',
  'estudiantes.colNivelRiesgo': 'Risk Level',
  'estudiantes.colAcciones': 'Actions',
  'estudiantes.sinDatos': 'No data',
  'estudiantes.verDetalles': 'View Details',
  'estudiantes.generarPrediccion': 'Generate Prediction',
  'estudiantes.eliminar': 'Delete',
  'estudiantes.modalTitle': 'Add New Student',
  'estudiantes.labelId': 'ID',
  'estudiantes.placeholderId': '1234567890',
  'estudiantes.labelNombres': 'First Names',
  'estudiantes.placeholderNombres': 'John',
  'estudiantes.labelApellidos': 'Last Names',
  'estudiantes.placeholderApellidos': 'Doe',
  'estudiantes.labelEmail': 'Email',
  'estudiantes.placeholderEmail': 'student@university.edu',
  'estudiantes.labelSemestre': 'Current Semester',
  'estudiantes.placeholderSemestre': 'Enter current semester (e.g. 1)',
  'estudiantes.titleSemestre': 'Student current semester',
  'estudiantes.cancelar': 'Cancel',
  'estudiantes.guardando': 'Saving...',
  'estudiantes.guardarEstudiante': 'Save Student',
  'estudiantes.limpiarBusqueda': 'Clear search',
  'estudiantes.resultadosBusqueda': 'Showing {count} result(s) for "{term}"',
  'estudiantes.registrados': 'students registered',
  'estudiantes.activos': 'Active',
  'estudiantes.enRiesgo': 'At Risk',
  'estudiantes.semestrePromedio': 'Average Semester',
  'estudiantes.bienvenidaVacio': 'Welcome,',
  'estudiantes.noEstudiantesRegistrados': 'No students have been registered in the system yet.',
  'estudiantes.agregarPrimero': 'Add the first student',
  'estudiantes.noResultados': 'No results found',
  'estudiantes.noCoincidencias': 'No students match your search for "{term}".',
  'estudiantes.modalPrimerEstudiante': 'Perfect {userName}! Let\'s register the first student.',
  'estudiantes.modalAgregarEstudiante': 'Adding student #{number} to the system',
  'login.completeCampos': 'Please complete all fields',
  'login.errorIniciar': 'Login error',
  'login.email': 'Email',
  'login.emailPlaceholder': 'user@university.edu',
  'login.password': 'Password',
  'login.passwordPlaceholder': '••••••••',
  'login.iniciando': 'Signing in...',
  'login.iniciarSesion': 'Sign In',
  'login.noTienesCuenta': 'Don\'t have an account?',
  'login.registrateAqui': 'Register here',
  'login.demo': 'Demo',
  'login.demoDescription': 'Use any email/password to access in demo mode.',
  'estudiantes.errorCargar': 'Error loading students',
  'estudiantes.completeCampos': 'Please complete all required fields',
  'estudiantes.errorCrear': 'Error creating student',
  'estudiantes.verDetallesDe': 'View details for',
  'estudiantes.enDesarrollo': 'This functionality is under development.',
  'estudiantes.generandoPara': 'Generating prediction for',
  'estudiantes.confirmEliminar': 'Are you sure you want to delete',
  'estudiantes.errorEliminar': 'Error deleting student',
    'predicciones.title': 'Risk Predictions',
    'predicciones.subtitle': 'Academic risk analysis for students',
  'predicciones.generarNuevas': 'Generate New Predictions',
  'predicciones.alertGenerarNuevas': 'Generating new predictions for all students...\nThis functionality will be available when the backend is complete.',
  'predicciones.verDetallesDe': 'View prediction details',
  'predicciones.errorDescargar': 'Report is not available yet',
  'predicciones.confirmRecalcular': 'Do you want to recalculate the prediction for',
  'predicciones.recalculando': 'Recalculating prediction...',
  'predicciones.generadasTitulo': 'Generated Predictions',
  'predicciones.filtrarLabel': 'Filter predictions by risk level',
  'predicciones.optionTodos': 'All levels',
  'predicciones.optionAlto': 'High Risk',
  'predicciones.optionMedio': 'Medium Risk',
  'predicciones.optionBajo': 'Low Risk',
  'predicciones.fecha': 'Date',
  'predicciones.factoresClave': 'Key Factors',
  'predicciones.verDetalles': 'View Details',
  'predicciones.descargando': 'Downloading...',
  'predicciones.generarReporte': 'Generate Report',
  'predicciones.recalcular': 'Recalculate',
  'predicciones.noEncontradas': 'No predictions found for the selected filter.',
  'predicciones.nuevaPrediccion': 'New Prediction',
  'predicciones.seleccionarEstudiante': 'Select Student',
  'predicciones.seleccioneEstudiante': 'Please select a student',
  'predicciones.seleccioneOpcion': 'Select an option...',
  'predicciones.notasPromedio': 'Grade Average',
  'predicciones.rangoNotasPromedio': 'Scale from 0.0 to 10.0',
  'predicciones.asistencia': 'Attendance (%)',
  'predicciones.rangoAsistencia': 'Percentage from 0 to 100',
  'predicciones.horasEstudio': 'Weekly Study Hours',
  'predicciones.rangoHorasEstudio': 'Hours per week',
  'predicciones.participacion': 'Class Participation',
  'predicciones.participacionBaja': 'Low',
  'predicciones.participacionMedia': 'Medium',
  'predicciones.participacionAlta': 'High',
  'predicciones.entregas': 'Homework Submission (%)',
  'predicciones.rangoEntregas': 'Percentage from 0 to 100',
  'predicciones.examenes': 'Exam Average',
  'predicciones.rangoExamenes': 'Scale from 0.0 to 10.0',
  'predicciones.prediccionCreada': 'Prediction created successfully',
  'predicciones.errorCrear': 'Error creating prediction',
  'common.cancelar': 'Cancel',
  'common.guardar': 'Save',
  'common.guardando': 'Saving...',
  'register.title': 'Create Account',
  'register.subtitle': 'Academic Prediction System',
  'register.nombres': 'First Names',
  'register.apellidos': 'Last Names',
  'register.email': 'Email',
  'register.password': 'Password',
  'register.confirmPassword': 'Confirm Password',
  'register.placeholderNombres': 'John',
  'register.placeholderApellidos': 'Doe',
  'register.placeholderEmail': 'user@university.edu',
  'register.placeholderPassword': '••••••••',
  'register.registrando': 'Registering...',
  'register.registrarse': 'Register',
  'register.yaTienesCuenta': 'Already have an account?',
  'register.iniciaSesion': 'Sign in here',
  'register.completeCampos': 'Please complete all fields',
  'register.passwordNoCoincide': 'Passwords do not match',
  'register.passwordMinLength': 'Password must be at least 6 characters',
  'profile.title': 'Edit profile',
  'profile.nombres': 'First Names',
  'profile.apellidos': 'Last Names',
  'profile.email': 'Email',
  'profile.telefono': 'Phone',
  'profile.direccion': 'Address',
  'profile.fechaNacimiento': 'Date of Birth',
  'profile.emailNoEditable': 'Email cannot be modified',
  'profile.camposNoEditables': 'ID, semester, major and GPA are managed by the institution',
  'profile.actualizado': 'Profile updated successfully',
  'profile.errorActualizar': 'Error updating profile',
  'profile.actualizando': 'Updating...',
  'profile.actualizar': 'Update',
  'profile.cerrar': 'Close',
  'footer.info': 'University · Institutional information',
  'footer.soporte': 'Support',
  'footer.politicas': 'Policies',
  'calificaciones.title': 'Grade Registration',
  'calificaciones.asignatura': 'Subject',
  'calificaciones.estudiante': 'Student',
  'calificaciones.periodo': 'Academic Period',
  'calificaciones.tipoEvaluacion': 'Evaluation Type',
  'calificaciones.nota': 'Grade',
  'calificaciones.registrar': 'Register Grade',
  'calificaciones.seleccionar': 'Select...',
  'calificaciones.acciones': 'Actions',
  'calificaciones.editar': 'Edit',
  'calificaciones.eliminar': 'Delete',
  'calificaciones.fecha': 'Date',
  'calificaciones.historial': 'Grade History',
  'estudiante.portalTitle': 'Student Portal',
  'estudiante.bienvenido': 'Welcome',
  'estudiante.cerrarSesion': 'Sign out',
  'estudiante.promedioGeneral': 'Overall Average',
  'estudiante.nivelRiesgo': 'Risk Level',
  'estudiante.materias': 'Subjects',
  'estudiante.asistenciaPromedio': 'Average Attendance',
  'estudiante.misCalificaciones': 'My Grades',
  'estudiante.miAsistencia': 'My Attendance',
  'estudiante.semestre': 'Semester',
  'estudiante.recomendacionesPersonalizadas': 'Personalized Recommendations',
  'estudiante.riesgoBajo': 'Low',
  'estudiante.riesgoMedio': 'Medium',
  'estudiante.riesgoAlto': 'High',
  'estudiante.recomendacion1': 'Keep up the good work in Programming',
  'estudiante.recomendacion2': 'Strengthen your knowledge in Physics',
  'estudiante.recomendacion3': 'Improve your attendance in Physics',
  'estudiante.recomendacion4': 'Continue with your excellent overall attendance',
  'dashboard.distribucionRiesgo': 'Risk Distribution',
  'dashboard.riesgoBajo': 'Low Risk',
  'dashboard.riesgoMedio': 'Medium Risk',
  'dashboard.accionesRapidas': 'Quick Actions',
  },
};

const LanguageContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}>({
  lang: 'es',
  setLang: () => {},
  t: (k: string) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const savedLang = localStorage.getItem('lang') as Lang;
    return savedLang && (savedLang === 'es' || savedLang === 'en') ? savedLang : 'es';
  });

  useEffect(() => {
    localStorage.setItem('lang', lang);
    // Forzar re-render de todos los componentes cuando cambie el idioma
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string) => {
    const translation = translations[lang][key];
    if (translation) {
      return translation;
    }
    // Fallback al español si no encuentra la traducción en el idioma actual
    return translations['es'][key] ?? key;
  };

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
